name: Mobile Tests CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Appium and UIAutomator2 driver
      run: |
        npm install -g appium
        appium driver install uiautomator2
        appium -v

    - name: Start Appium server
      run: |
        nohup appium --base-path /wd/hub --log-level info > appium.log 2>&1 &
        sleep 10
        
    - name: Check Appium Server is up
      run: |
        curl http://127.0.0.1:4723/wd/hub/status

    - name: Start Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: pixel
        script: echo "📱 Emulator is running"

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Wait for emulator to boot
      run: |
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        boot_status=""
        retry=0
        while [ "$boot_status" != "1" ] && [ $retry -lt 30 ]; do
          echo "Checking if emulator booted... attempt $retry"
          boot_status=$(adb -s emulator-5554 shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
          sleep 5
          retry=$((retry+1))
        done
        if [ "$boot_status" != "1" ]; then
          echo "❌ Emulator did not boot in time"
          exit 1
        fi
        echo "✅ Emulator booted successfully"

    - name: Build
      run: dotnet build --no-restore

    - name: Run MobileAndroid tests
      run: dotnet test --filter "TestCategory=MobileAndroid"

    - name: Print Appium logs
      if: always()
      run: |
        echo "========= Appium Logs ========="
        cat appium.log || echo "No log file found"
