name: Android Emulator CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Start Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: pixel
        script: |
          echo "📱 Emulator is up and running"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Appium
      run: |
        npm install -g appium
        appium -v

    - name: Print environment info (debug)
      run: |
        adb devices
        echo "🎯 Appium ready, emulator ready"
